// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_demo_contracts::day {
    use std::string::String;
    use sui_demo_contracts::month::Month;
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;

    struct Day has store, drop, copy {
        month: Month,
        number: u8,
        time_zone: String,
    }

    public fun new(
        month: Month,
        number: u8,
        time_zone: String,
    ): Day {
        let day = Day {
            month,
            number,
            time_zone,
        };
        validate(&day);
        day
    }

    fun validate(day: &Day) {
        assert!(std::string::length(&day.time_zone) <= 50, EDataTooLong);
    }

    public fun month(day: &Day): Month {
        day.month
    }

    public fun number(day: &Day): u8 {
        day.number
    }

    public fun time_zone(day: &Day): String {
        day.time_zone
    }

}
