// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_demo_contracts::day_summary_created {

    use std::option::{Self, Option};
    use std::string::String;
    use sui::object;
    use sui_demo_contracts::day::Day;
    use sui_demo_contracts::day_summary::{Self, DaySummaryCreated};

    public fun id(day_summary_created: &DaySummaryCreated): option::Option<object::ID> {
        day_summary::day_summary_created_id(day_summary_created)
    }

    public fun day(day_summary_created: &DaySummaryCreated): Day {
        day_summary::day_summary_created_day(day_summary_created)
    }

    public fun description(day_summary_created: &DaySummaryCreated): String {
        day_summary::day_summary_created_description(day_summary_created)
    }

    public fun meta_data(day_summary_created: &DaySummaryCreated): vector<u8> {
        day_summary::day_summary_created_meta_data(day_summary_created)
    }

    public fun array_data(day_summary_created: &DaySummaryCreated): vector<String> {
        day_summary::day_summary_created_array_data(day_summary_created)
    }

    public fun optional_data(day_summary_created: &DaySummaryCreated): Option<vector<u8>> {
        day_summary::day_summary_created_optional_data(day_summary_created)
    }

}
