// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_demo_contracts::order_item_removed {

    use std::string::String;
    use sui::object;
    use sui_demo_contracts::order::{Self, OrderItemRemoved};

    public fun id(order_item_removed: &OrderItemRemoved): object::ID {
        order::order_item_removed_id(order_item_removed)
    }

    public fun product_id(order_item_removed: &OrderItemRemoved): String {
        order::order_item_removed_product_id(order_item_removed)
    }

}
