// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_contracts::order_deleted {

    use sui::object;
    use sui_contracts::order::{Self, OrderDeleted};

    public fun id(order_deleted: &OrderDeleted): object::ID {
        order::order_deleted_id(order_deleted)
    }

}
