// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_demo_contracts::player {
    use std::option;
    use std::string::String;
    use sui::event;
    use sui::object::{Self, UID};
    use sui::table;
    use sui::transfer;
    use sui::tx_context::TxContext;
    friend sui_demo_contracts::player_create_logic;
    friend sui_demo_contracts::player_update_logic;
    friend sui_demo_contracts::player_delete_logic;
    friend sui_demo_contracts::player_aggregate;

    const EIdAlreadyExists: u64 = 101;
    #[allow(unused_const)]
    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const EEmptyObjectID: u64 = 107;

    struct PlayerIdTable has key {
        id: UID,
        table: table::Table<address, object::ID>,
    }

    struct PlayerIdTableCreated has copy, drop {
        id: object::ID,
    }

    fun init(ctx: &mut TxContext) {
        let id_generator_table = PlayerIdTable {
            id: object::new(ctx),
            table: table::new(ctx),
        };
        let id_generator_table_id = object::uid_to_inner(&id_generator_table.id);
        transfer::share_object(id_generator_table);
        event::emit(PlayerIdTableCreated {
            id: id_generator_table_id,
        });
    }

    struct Player has key {
        id: UID,
        player_id: address,
        version: u64,
        nickname: std::ascii::String,
        intro: String,
    }

    public fun id(player: &Player): object::ID {
        object::uid_to_inner(&player.id)
    }

    public fun player_id(player: &Player): address {
        player.player_id
    }

    public fun version(player: &Player): u64 {
        player.version
    }

    public fun nickname(player: &Player): std::ascii::String {
        player.nickname
    }

    public(friend) fun set_nickname(player: &mut Player, nickname: std::ascii::String) {
        player.nickname = nickname;
    }

    public fun intro(player: &Player): String {
        player.intro
    }

    public(friend) fun set_intro(player: &mut Player, intro: String) {
        assert!(std::string::length(&intro) <= 350, EDataTooLong);
        player.intro = intro;
    }

    fun new_player(
        player_id: address,
        nickname: std::ascii::String,
        intro: String,
        ctx: &mut TxContext,
    ): Player {
        assert!(std::string::length(&intro) <= 350, EDataTooLong);
        Player {
            id: object::new(ctx),
            player_id,
            version: 0,
            nickname,
            intro,
        }
    }

    struct PlayerCreated has copy, drop {
        id: option::Option<object::ID>,
        player_id: address,
        nickname: std::ascii::String,
        intro: String,
    }

    public fun player_created_id(player_created: &PlayerCreated): option::Option<object::ID> {
        player_created.id
    }

    public(friend) fun set_player_created_id(player_created: &mut PlayerCreated, id: object::ID) {
        player_created.id = option::some(id);
    }

    public fun player_created_player_id(player_created: &PlayerCreated): address {
        player_created.player_id
    }

    public fun player_created_nickname(player_created: &PlayerCreated): std::ascii::String {
        player_created.nickname
    }

    public fun player_created_intro(player_created: &PlayerCreated): String {
        player_created.intro
    }

    public(friend) fun new_player_created(
        player_id: address,
        nickname: std::ascii::String,
        intro: String,
    ): PlayerCreated {
        PlayerCreated {
            id: option::none(),
            player_id,
            nickname,
            intro,
        }
    }

    struct PlayerUpdated has copy, drop {
        id: object::ID,
        player_id: address,
        version: u64,
        nickname: std::ascii::String,
        intro: String,
    }

    public fun player_updated_id(player_updated: &PlayerUpdated): object::ID {
        player_updated.id
    }

    public fun player_updated_player_id(player_updated: &PlayerUpdated): address {
        player_updated.player_id
    }

    public fun player_updated_nickname(player_updated: &PlayerUpdated): std::ascii::String {
        player_updated.nickname
    }

    public fun player_updated_intro(player_updated: &PlayerUpdated): String {
        player_updated.intro
    }

    public(friend) fun new_player_updated(
        player: &Player,
        nickname: std::ascii::String,
        intro: String,
    ): PlayerUpdated {
        PlayerUpdated {
            id: id(player),
            player_id: player_id(player),
            version: version(player),
            nickname,
            intro,
        }
    }

    struct PlayerDeleted has copy, drop {
        id: object::ID,
        player_id: address,
        version: u64,
    }

    public fun player_deleted_id(player_deleted: &PlayerDeleted): object::ID {
        player_deleted.id
    }

    public fun player_deleted_player_id(player_deleted: &PlayerDeleted): address {
        player_deleted.player_id
    }

    public(friend) fun new_player_deleted(
        player: &Player,
    ): PlayerDeleted {
        PlayerDeleted {
            id: id(player),
            player_id: player_id(player),
            version: version(player),
        }
    }


    public(friend) fun create_player(
        player_id: address,
        nickname: std::ascii::String,
        intro: String,
        player_id_table: &mut PlayerIdTable,
        ctx: &mut TxContext,
    ): Player {
        let player = new_player(
            player_id,
            nickname,
            intro,
            ctx,
        );
        asset_player_id_not_exists_then_add(player_id, player_id_table, object::uid_to_inner(&player.id));
        player
    }

    public(friend) fun asset_player_id_not_exists(
        player_id: address,
        player_id_table: &PlayerIdTable,
    ) {
        assert!(!table::contains(&player_id_table.table, player_id), EIdAlreadyExists);
    }

    fun asset_player_id_not_exists_then_add(
        player_id: address,
        player_id_table: &mut PlayerIdTable,
        id: object::ID,
    ) {
        asset_player_id_not_exists(player_id, player_id_table);
        table::add(&mut player_id_table.table, player_id, id);
    }

    public(friend) fun transfer_object(player: Player, recipient: address) {
        assert!(player.version == 0, EInappropriateVersion);
        transfer::transfer(player, recipient);
    }

    public(friend) fun update_version_and_transfer_object(player: Player, recipient: address) {
        update_object_version(&mut player);
        transfer::transfer(player, recipient);
    }

    #[lint_allow(share_owned)]
    public(friend) fun share_object(player: Player) {
        assert!(player.version == 0, EInappropriateVersion);
        transfer::share_object(player);
    }

    public(friend) fun freeze_object(player: Player) {
        assert!(player.version == 0, EInappropriateVersion);
        transfer::freeze_object(player);
    }

    public(friend) fun update_version_and_freeze_object(player: Player) {
        update_object_version(&mut player);
        transfer::freeze_object(player);
    }

    fun update_object_version(player: &mut Player) {
        player.version = player.version + 1;
        //assert!(player.version != 0, EInappropriateVersion);
    }

    public(friend) fun drop_player(player: Player) {
        let Player {
            id,
            player_id: _player_id,
            version: _version,
            nickname: _nickname,
            intro: _intro,
        } = player;
        object::delete(id);
    }

    public(friend) fun emit_player_created(player_created: PlayerCreated) {
        assert!(std::option::is_some(&player_created.id), EEmptyObjectID);
        event::emit(player_created);
    }

    public(friend) fun emit_player_updated(player_updated: PlayerUpdated) {
        event::emit(player_updated);
    }

    public(friend) fun emit_player_deleted(player_deleted: PlayerDeleted) {
        event::emit(player_deleted);
    }

    #[test_only]
    /// Wrapper of module initializer for testing
    public fun test_init(ctx: &mut TxContext) {
        init(ctx)
    }

}
