// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_contracts::product_deleted {

    use std::string::String;
    use sui::object;
    use sui_contracts::product::{Self, ProductDeleted};

    public fun id(product_deleted: &ProductDeleted): object::ID {
        product::product_deleted_id(product_deleted)
    }

    public fun product_id(product_deleted: &ProductDeleted): String {
        product::product_deleted_product_id(product_deleted)
    }

}
