// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_contracts::product_updated {

    use std::string::String;
    use sui::object;
    use sui_contracts::product::{Self, ProductUpdated};

    public fun id(product_updated: &ProductUpdated): object::ID {
        product::product_updated_id(product_updated)
    }

    public fun product_id(product_updated: &ProductUpdated): String {
        product::product_updated_product_id(product_updated)
    }

    public fun name(product_updated: &ProductUpdated): String {
        product::product_updated_name(product_updated)
    }

    public fun unit_price(product_updated: &ProductUpdated): u128 {
        product::product_updated_unit_price(product_updated)
    }

    public fun owner(product_updated: &ProductUpdated): address {
        product::product_updated_owner(product_updated)
    }

}
