processed 17 tasks

task 4 'run'. lines 9-23:
{
  "gas_used": 145224,
  "status": "Executed"
}

task 5 'block'. lines 25-25:
Error: Transaction discarded. VMStatus: status UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION of type Invariant violation

task 6 'run'. lines 27-64:
{
  "gas_used": 310432,
  "status": {
    "MoveAbort": {
      "location": "Script",
      "abort_code": "1001"
    }
  }
}

task 7 'run'. lines 67-104:
{
  "gas_used": 29752,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 8 'run'. lines 108-146:
{
  "gas_used": 33623,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 9 'run'. lines 149-188:
{
  "gas_used": 37752,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 10 'run'. lines 191-229:
{
  "gas_used": 33881,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 11 'run'. lines 232-271:
{
  "gas_used": 38162,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 12 'run'. lines 274-314:
{
  "gas_used": 41881,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 13 'run'. lines 318-360:
{
  "gas_used": 57558,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 14 'run'. lines 363-405:
{
  "gas_used": 57558,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 15 'run'. lines 408-447:
{
  "gas_used": 44411,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}

task 16 'run'. lines 450-493:
{
  "gas_used": 61447,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x18351d311d32201149a4df2a9fc2db8a",
          "name": "DomainNameAggregate"
        }
      },
      "abort_code": "26119"
    }
  }
}
