[package]
name = "Examples"
version = "0.0.0"

[addresses]
hello_table = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "aptos-cli-v1.0.11", subdir = "aptos-move/framework/aptos-framework" }
