// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::article_created {

    use moveos_std::object::ObjectID;
    use rooch_demo::article::{Self, ArticleCreated};
    use rooch_demo::reference_vo::ReferenceVO;
    use std::option;
    use std::string::String;

    public fun id(article_created: &ArticleCreated): option::Option<ObjectID> {
        article::article_created_id(article_created)
    }

    public fun title(article_created: &ArticleCreated): String {
        article::article_created_title(article_created)
    }

    public fun author(article_created: &ArticleCreated): address {
        article::article_created_author(article_created)
    }

    public fun content(article_created: &ArticleCreated): String {
        article::article_created_content(article_created)
    }

    public fun references(article_created: &ArticleCreated): vector<ReferenceVO> {
        article::article_created_references(article_created)
    }

    public fun tags(article_created: &ArticleCreated): vector<ObjectID> {
        article::article_created_tags(article_created)
    }

    public fun owner(article_created: &ArticleCreated): address {
        article::article_created_owner(article_created)
    }

}
