// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::create_event {

    use rooch_demo::tag::{Self, CreateEvent};
    use std::string::String;

    public fun name(create_event: &CreateEvent): String {
        tag::create_event_name(create_event)
    }

}
