// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::day_summary_aggregate {
    use moveos_std::object_id::ObjectID;
    use moveos_std::storage_context::StorageContext;
    use rooch_demo::day::{Self, Day};
    use rooch_demo::day_summary;
    use rooch_demo::day_summary_create_logic;
    use rooch_demo::day_summary_delete_logic;
    use rooch_demo::month;
    use rooch_demo::year;
    use std::option::{Self, Option};
    use std::string::String;
    use std::vector;

    public entry fun create(
        storage_ctx: &mut StorageContext,
        account: &signer,
        day_month_year_number: u16,
        day_month_year_calendar: String,
        day_month_number: u8,
        day_month_is_leap: bool,
        day_number: u8,
        day_time_zone: String,
        description: String,
        meta_data: vector<u8>,
        array_data: vector<String>,
        optional_data: vector<String>,
        u16_array_data: vector<u16>,
        u32_array_data: vector<u32>,
        u64_array_data: vector<u64>,
        u128_array_data: vector<u128>,
        u256_array_data: vector<u256>,
    ) {
        let day: Day = day::new(
            month::new(
                year::new(
                    day_month_year_number,
                    day_month_year_calendar,
                ),
                day_month_number,
                day_month_is_leap,
            ),
            day_number,
            day_time_zone,
        );

        let day_summary_created = day_summary_create_logic::verify(
            storage_ctx,
            account,
            day,
            description,
            meta_data,
            array_data,
            vector_to_option(optional_data),
            u16_array_data,
            u32_array_data,
            u64_array_data,
            u128_array_data,
            u256_array_data,
        );
        let day_summary_obj = day_summary_create_logic::mutate(
            storage_ctx,
            &day_summary_created,
        );
        day_summary::set_day_summary_created_id(&mut day_summary_created, day_summary::id(&day_summary_obj));
        day_summary::add_day_summary(storage_ctx, day_summary_obj);
        day_summary::emit_day_summary_created(storage_ctx, day_summary_created);
    }


    public entry fun delete(
        storage_ctx: &mut StorageContext,
        account: &signer,
        id: ObjectID,
    ) {
        let day_summary_obj = day_summary::remove_day_summary(storage_ctx, id);
        let day_summary_deleted = day_summary_delete_logic::verify(
            storage_ctx,
            account,
            &day_summary_obj,
        );
        let updated_day_summary_obj = day_summary_delete_logic::mutate(
            storage_ctx,
            &day_summary_deleted,
            day_summary_obj,
        );
        day_summary::drop_day_summary(updated_day_summary_obj);
        day_summary::emit_day_summary_deleted(storage_ctx, day_summary_deleted);
    }

    fun vector_to_option<V : drop>(v: vector<V>): Option<V> {
        if (vector::length(&v) == 0) { option::none() } else {
            option::some(
                vector::pop_back(&mut v)
            )
        }
    }

}
