// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::order_item_ship_group_assoc_subitem_added {

    use moveos_std::object_id::ObjectID;
    use rooch_demo::day::Day;
    use rooch_demo::order::{Self, OrderItemShipGroupAssocSubitemAdded};
    use std::string::String;

    public fun id(order_item_ship_group_assoc_subitem_added: &OrderItemShipGroupAssocSubitemAdded): ObjectID {
        order::order_item_ship_group_assoc_subitem_added_id(order_item_ship_group_assoc_subitem_added)
    }

    public fun order_id(order_item_ship_group_assoc_subitem_added: &OrderItemShipGroupAssocSubitemAdded): String {
        order::order_item_ship_group_assoc_subitem_added_order_id(order_item_ship_group_assoc_subitem_added)
    }

    public fun ship_group_seq_id(order_item_ship_group_assoc_subitem_added: &OrderItemShipGroupAssocSubitemAdded): u8 {
        order::order_item_ship_group_assoc_subitem_added_ship_group_seq_id(order_item_ship_group_assoc_subitem_added)
    }

    public fun product_obj_id(order_item_ship_group_assoc_subitem_added: &OrderItemShipGroupAssocSubitemAdded): ObjectID {
        order::order_item_ship_group_assoc_subitem_added_product_obj_id(order_item_ship_group_assoc_subitem_added)
    }

    public fun day(order_item_ship_group_assoc_subitem_added: &OrderItemShipGroupAssocSubitemAdded): Day {
        order::order_item_ship_group_assoc_subitem_added_day(order_item_ship_group_assoc_subitem_added)
    }

    public fun description(order_item_ship_group_assoc_subitem_added: &OrderItemShipGroupAssocSubitemAdded): String {
        order::order_item_ship_group_assoc_subitem_added_description(order_item_ship_group_assoc_subitem_added)
    }

}
