// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::order_created {

    use moveos_std::object_id::ObjectID;
    use rooch_demo::order::{Self, OrderCreated};
    use std::option;
    use std::string::String;

    public fun id(order_created: &OrderCreated): option::Option<ObjectID> {
        order::order_created_id(order_created)
    }

    public fun order_id(order_created: &OrderCreated): String {
        order::order_created_order_id(order_created)
    }

    public fun product_obj_id(order_created: &OrderCreated): ObjectID {
        order::order_created_product_obj_id(order_created)
    }

    public fun quantity(order_created: &OrderCreated): u64 {
        order::order_created_quantity(order_created)
    }

    public fun unit_price(order_created: &OrderCreated): u128 {
        order::order_created_unit_price(order_created)
    }

    public fun total_amount(order_created: &OrderCreated): u128 {
        order::order_created_total_amount(order_created)
    }

    public fun owner(order_created: &OrderCreated): address {
        order::order_created_owner(order_created)
    }

}
