// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::order_item_removed {

    use moveos_std::object::ObjectID;
    use rooch_demo::order::{Self, OrderItemRemoved};
    use std::string::String;

    public fun id(order_item_removed: &OrderItemRemoved): ObjectID {
        order::order_item_removed_id(order_item_removed)
    }

    public fun order_id(order_item_removed: &OrderItemRemoved): String {
        order::order_item_removed_order_id(order_item_removed)
    }

    public fun product_obj_id(order_item_removed: &OrderItemRemoved): ObjectID {
        order::order_item_removed_product_obj_id(order_item_removed)
    }

}
