// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::reference_added {

    use moveos_std::object_id::ObjectID;
    use rooch_demo::article::{Self, ReferenceAdded};
    use std::option::Option;
    use std::string::String;

    public fun id(reference_added: &ReferenceAdded): ObjectID {
        article::reference_added_id(reference_added)
    }

    public fun reference_number(reference_added: &ReferenceAdded): u64 {
        article::reference_added_reference_number(reference_added)
    }

    public fun title(reference_added: &ReferenceAdded): String {
        article::reference_added_title(reference_added)
    }

    public fun url(reference_added: &ReferenceAdded): Option<String> {
        article::reference_added_url(reference_added)
    }

}
