// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::reference_vo {
    use std::option::Option;
    use std::string::String;
    const EID_DATA_TOO_LONG: u64 = 102;

    struct ReferenceVO has store, drop, copy {
        reference_number: u64,
        title: String,
        url: Option<String>,
    }

    public fun new(
        reference_number: u64,
        title: String,
        url: Option<String>,
    ): ReferenceVO {
        ReferenceVO {
            reference_number,
            title,
            url,
        }
    }

    public fun reference_number(reference_vo: &ReferenceVO): u64 {
        reference_vo.reference_number
    }

    public fun title(reference_vo: &ReferenceVO): String {
        reference_vo.title
    }

    public fun url(reference_vo: &ReferenceVO): Option<String> {
        reference_vo.url
    }

}
