// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::tag_aggregate {
    use moveos_std::storage_context::StorageContext;
    use rooch_demo::tag;
    use rooch_demo::tag_create_logic;
    use std::string::String;

    public entry fun create(
        storage_ctx: &mut StorageContext,
        account: &signer,
        name: String,
    ) {
        let tag_created = tag_create_logic::verify(
            storage_ctx,
            account,
            name,
        );
        let tag_obj = tag_create_logic::mutate(
            storage_ctx,
            account,
            &tag_created,
        );
        tag::set_tag_created_id(&mut tag_created, tag::id(&tag_obj));
        tag::add_tag(storage_ctx, tag_obj);
        tag::emit_tag_created(storage_ctx, tag_created);
    }

}
