// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module rooch_demo::tag_created {

    use rooch_demo::tag::{Self, TagCreated};
    use std::string::String;

    public fun name(tag_created: &TagCreated): String {
        tag::tag_created_name(tag_created)
    }

}
