// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.domainname;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import org.dddml.suidemocontracts.sui.contract.*;

import java.math.*;
import java.util.*;

@JsonNaming(PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy.class)
public class Renewed {
    private String id;

    private DomainNameId domainNameId;

    private Long version;

    private BigInteger renewPeriod;

    private String account;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public DomainNameId getDomainNameId() {
        return domainNameId;
    }

    public void setDomainNameId(DomainNameId domainNameId) {
        this.domainNameId = domainNameId;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public BigInteger getRenewPeriod() {
        return renewPeriod;
    }

    public void setRenewPeriod(BigInteger renewPeriod) {
        this.renewPeriod = renewPeriod;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    @Override
    public String toString() {
        return "Renewed{" +
                "id='" + id + '\'' +
                ", domainNameId=" + domainNameId +
                ", version=" + version +
                ", renewPeriod=" + renewPeriod +
                ", account=" + '\'' + account + '\'' +
                '}';
    }

}
