// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract;

public class DomainBeanUtils {
    private DomainBeanUtils() {
    }

    public static org.dddml.suidemocontracts.domain.Day toDay(Day contractDay) {
        org.dddml.suidemocontracts.domain.Day day = new org.dddml.suidemocontracts.domain.Day();
        day.setMonth(toMonth(contractDay.getFields().getMonth()));
        day.setNumber(contractDay.getFields().getNumber());
        day.setTimeZone(contractDay.getFields().getTimeZone());
        return day;
    }

    public static org.dddml.suidemocontracts.domain.domainname.DomainNameId toDomainNameId(DomainNameId contractDomainNameId) {
        org.dddml.suidemocontracts.domain.domainname.DomainNameId domainNameId = new org.dddml.suidemocontracts.domain.domainname.DomainNameId();
        domainNameId.setTopLevelDomain(contractDomainNameId.getFields().getTopLevelDomain());
        domainNameId.setSecondLevelDomain(contractDomainNameId.getFields().getSecondLevelDomain());
        return domainNameId;
    }

    public static org.dddml.suidemocontracts.domain.Month toMonth(Month contractMonth) {
        org.dddml.suidemocontracts.domain.Month month = new org.dddml.suidemocontracts.domain.Month();
        month.setYear(toYear(contractMonth.getFields().getYear()));
        month.setNumber(contractMonth.getFields().getNumber());
        month.setIsLeap(contractMonth.getFields().getIsLeap());
        return month;
    }

    public static org.dddml.suidemocontracts.domain.Year toYear(Year contractYear) {
        org.dddml.suidemocontracts.domain.Year year = new org.dddml.suidemocontracts.domain.Year();
        year.setNumber(contractYear.getFields().getNumber());
        year.setCalendar(contractYear.getFields().getCalendar());
        return year;
    }

}
