// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.github.wubuku.sui.bean.*;

import java.math.*;
import java.util.*;

@JsonNaming(PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy.class)
public class OrderItemShipGroupAssocSubitem {

    private Integer orderItemShipGroupAssocSubitemSeqId;

    private String description;

    public Integer getOrderItemShipGroupAssocSubitemSeqId() {
        return orderItemShipGroupAssocSubitemSeqId;
    }

    public void setOrderItemShipGroupAssocSubitemSeqId(Integer orderItemShipGroupAssocSubitemSeqId) {
        this.orderItemShipGroupAssocSubitemSeqId = orderItemShipGroupAssocSubitemSeqId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "OrderItemShipGroupAssocSubitem{" +
                "orderItemShipGroupAssocSubitemSeqId=" + orderItemShipGroupAssocSubitemSeqId +
                ", description=" + '\'' + description + '\'' +
                '}';
    }
}
