// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract;

import com.github.wubuku.sui.bean.DynamicField;

import java.math.*;

public class OrderItemShipGroupAssocSubitemDynamicField extends DynamicField<Integer, OrderItemShipGroupAssocSubitem> {

}
