// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.github.wubuku.sui.bean.*;

import java.math.*;
import java.util.*;

@JsonNaming(PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy.class)
public class OrderItemShipGroupAssociation {

    private String productId;

    private BigInteger quantity;

    private BigInteger cancelQuantity;

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public BigInteger getQuantity() {
        return quantity;
    }

    public void setQuantity(BigInteger quantity) {
        this.quantity = quantity;
    }

    public BigInteger getCancelQuantity() {
        return cancelQuantity;
    }

    public void setCancelQuantity(BigInteger cancelQuantity) {
        this.cancelQuantity = cancelQuantity;
    }

    @Override
    public String toString() {
        return "OrderItemShipGroupAssociation{" +
                "productId=" + '\'' + productId + '\'' +
                ", quantity=" + quantity +
                ", cancelQuantity=" + cancelQuantity +
                '}';
    }
}
