[package]
name = "AptosDemo"
version = "0.0.0"

[addresses]
aptos_demo = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
