spring:
  profiles:
    active: test

  main:
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false
    #show-sql: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  #      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    default-property-inclusion: NON_EMPTY

  messages:
    encoding: UTF-8
    basename: i18n/messages

  mvc:
    static-path-pattern: /**
    servlet:
      path: /api
      #load-on-startup: -1

server:

  compression:
    enabled: true
    min-response-size: 20480  #20K more with gzip on
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

  max-http-header-size: 81920

#  error:
#    whitelabel:
#      enabled: false
