// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.daysummary;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import org.dddml.suidemocontracts.sui.contract.*;

import java.math.*;
import java.util.*;

@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class DaySummaryCreated {
    private String id;

    private Day day;

    private String description;

    private int[] metaData;

    private String[] arrayData;

    private int[] optionalData;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Day getDay() {
        return day;
    }

    public void setDay(Day day) {
        this.day = day;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int[] getMetaData() {
        return metaData;
    }

    public void setMetaData(int[] metaData) {
        this.metaData = metaData;
    }

    public String[] getArrayData() {
        return arrayData;
    }

    public void setArrayData(String[] arrayData) {
        this.arrayData = arrayData;
    }

    public int[] getOptionalData() {
        return optionalData;
    }

    public void setOptionalData(int[] optionalData) {
        this.optionalData = optionalData;
    }

    @Override
    public String toString() {
        return "DaySummaryCreated{" +
                "id='" + id + '\'' +
                ", day=" + day +
                ", description=" + '\'' + description + '\'' +
                ", metaData=" + Arrays.toString(metaData) +
                ", arrayData=" + Arrays.toString(arrayData) +
                ", optionalData=" + Arrays.toString(optionalData) +
                '}';
    }

}
