// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.repository;

import org.dddml.suidemocontracts.domain.domainname.*;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DomainNameEventRepository extends JpaRepository<AbstractDomainNameEvent, DomainNameEventId> {
    AbstractDomainNameEvent.Registered findFirstRegisteredByOrderBySuiTimestampDesc();

    AbstractDomainNameEvent.Renewed findFirstRenewedByOrderBySuiTimestampDesc();

}
