// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.repository;

import org.dddml.suidemocontracts.domain.order.*;
import org.springframework.data.jpa.repository.JpaRepository;

public interface OrderEventRepository extends JpaRepository<AbstractOrderEvent, OrderEventId> {
    AbstractOrderEvent.OrderCreated findFirstOrderCreatedByOrderBySuiTimestampDesc();

    AbstractOrderEvent.OrderItemRemoved findFirstOrderItemRemovedByOrderBySuiTimestampDesc();

    AbstractOrderEvent.OrderItemQuantityUpdated findFirstOrderItemQuantityUpdatedByOrderBySuiTimestampDesc();

}
