// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.repository;

import org.dddml.suidemocontracts.domain.orderv2.*;
import org.springframework.data.jpa.repository.JpaRepository;

public interface OrderV2EventRepository extends JpaRepository<AbstractOrderV2Event, OrderV2EventId> {
    AbstractOrderV2Event.OrderV2Created findFirstOrderV2CreatedByOrderBySuiTimestampDesc();

    AbstractOrderV2Event.OrderV2ItemRemoved findFirstOrderV2ItemRemovedByOrderBySuiTimestampDesc();

    AbstractOrderV2Event.OrderV2ItemQuantityUpdated findFirstOrderV2ItemQuantityUpdatedByOrderBySuiTimestampDesc();

    AbstractOrderV2Event.OrderV2EstimatedShipDateUpdated findFirstOrderV2EstimatedShipDateUpdatedByOrderBySuiTimestampDesc();

    AbstractOrderV2Event.OrderShipGroupAdded findFirstOrderShipGroupAddedByOrderBySuiTimestampDesc();

    AbstractOrderV2Event.OrderShipGroupQuantityCanceled findFirstOrderShipGroupQuantityCanceledByOrderBySuiTimestampDesc();

}
