// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.repository;

import org.dddml.suidemocontracts.domain.product.*;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ProductEventRepository extends JpaRepository<AbstractProductEvent, ProductEventId> {
    AbstractProductEvent.ProductCreated findFirstProductCreatedByOrderBySuiTimestampDesc();

}
