spring:
#  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456
server:
  port: 1023
