// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::day_summary_aggregate {
    use aptos_demo::day::{Self, Day};
    use aptos_demo::day_summary;
    use aptos_demo::day_summary_create_logic;
    use aptos_demo::month;
    use aptos_demo::year;
    use std::option::{Self, Option};
    use std::string::String;
    use std::vector;

    public entry fun create(
        account: &signer,
        day_month_year_number: u16,
        day_month_year_calendar: String,
        day_month_number: u8,
        day_month_is_leap: bool,
        day_number: u8,
        day_time_zone: String,
        description: String,
        meta_data: vector<u8>,
        array_data: vector<String>,
        optional_data: vector<String>,
        u16_array_data: vector<u16>,
        u32_array_data: vector<u32>,
        u64_array_data: vector<u64>,
        u128_array_data: vector<u128>,
        u256_array_data: vector<u256>,
    ) {
        let day: Day = day::new(
            month::new(
                year::new(
                    day_month_year_number,
                    day_month_year_calendar,
                ),
                day_month_number,
                day_month_is_leap,
            ),
            day_number,
            day_time_zone,
        );

        let day_summary_created = day_summary_create_logic::verify(
            account,
            day,
            description,
            meta_data,
            array_data,
            vector_to_option(optional_data),
            u16_array_data,
            u32_array_data,
            u64_array_data,
            u128_array_data,
            u256_array_data,
        );
        let day_summary = day_summary_create_logic::mutate(
            account,
            &day_summary_created,
        );
        day_summary::add_day_summary(day_summary);
        day_summary::emit_day_summary_created(day_summary_created);
    }

    fun vector_to_option<V : drop>(v: vector<V>): Option<V> {
        if (vector::length(&v) == 0) { option::none() } else {
            option::some(
                vector::pop_back(&mut v)
            )
        }
    }

}
