// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::order_item_ship_group_assoc_subitem {
    //use aptos_std::table::{Self, Table};
    use aptos_demo::day::Day;
    use std::string::String;
    friend aptos_demo::order_create_logic;
    friend aptos_demo::order_remove_item_logic;
    friend aptos_demo::order_update_item_quantity_logic;
    friend aptos_demo::order_item_ship_group_association;

    const EID_ALREADY_EXISTS: u64 = 101;
    const EID_DATA_TOO_LONG: u64 = 102;

    struct OrderItemShipGroupAssocSubitem has store {
        order_item_ship_group_assoc_subitem_day: Day,
        description: String,
    }

    public fun order_item_ship_group_assoc_subitem_day(order_item_ship_group_assoc_subitem: &OrderItemShipGroupAssocSubitem): Day {
        order_item_ship_group_assoc_subitem.order_item_ship_group_assoc_subitem_day
    }

    public fun description(order_item_ship_group_assoc_subitem: &OrderItemShipGroupAssocSubitem): String {
        order_item_ship_group_assoc_subitem.description
    }

    public(friend) fun set_description(order_item_ship_group_assoc_subitem: &mut OrderItemShipGroupAssocSubitem, description: String) {
        order_item_ship_group_assoc_subitem.description = description;
    }

    public(friend) fun new_order_item_ship_group_assoc_subitem(
        order_item_ship_group_assoc_subitem_day: Day,
        description: String,
    ): OrderItemShipGroupAssocSubitem {
        assert!(std::string::length(&description) <= 100, EID_DATA_TOO_LONG);
        OrderItemShipGroupAssocSubitem {
            order_item_ship_group_assoc_subitem_day,
            description,
        }
    }

    public(friend) fun drop_order_item_ship_group_assoc_subitem(order_item_ship_group_assoc_subitem: OrderItemShipGroupAssocSubitem) {
        let OrderItemShipGroupAssocSubitem {
            order_item_ship_group_assoc_subitem_day: _,
            description: _,
        } = order_item_ship_group_assoc_subitem;
    }


}
