// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::order_item_quantity_updated {

    use std::string::String;
    //use sui::object;
    use aptos_demo::order::{Self, OrderItemQuantityUpdated};

    public fun order_id(order_item_quantity_updated: &OrderItemQuantityUpdated): String {
        order::order_item_quantity_updated_order_id(order_item_quantity_updated)
    }

    public fun product_id(order_item_quantity_updated: &OrderItemQuantityUpdated): String {
        order::order_item_quantity_updated_product_id(order_item_quantity_updated)
    }

    public fun quantity(order_item_quantity_updated: &OrderItemQuantityUpdated): u64 {
        order::order_item_quantity_updated_quantity(order_item_quantity_updated)
    }

}
