// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

//
// RemoveOrderShipGroupItem event module is disabled.
// Use order module instead.
//
