// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::order_item_removed {

    use std::string::String;
    //use sui::object;
    use aptos_demo::order::{Self, OrderItemRemoved};

    public fun order_id(order_item_removed: &OrderItemRemoved): String {
        order::order_item_removed_order_id(order_item_removed)
    }

    public fun product_id(order_item_removed: &OrderItemRemoved): String {
        order::order_item_removed_product_id(order_item_removed)
    }

}
