// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::product_deleted {

    use aptos_demo::product::{Self, ProductDeleted};
    use std::string::String;

    public fun product_id(product_deleted: &ProductDeleted): String {
        product::product_deleted_product_id(product_deleted)
    }

}
