// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::product_aggregate {
    use std::string::String;

    use aptos_demo::product;
    use aptos_demo::product_create_logic;

    //use sui::tx_context;
    public entry fun create(
        _account: signer,
        name: String,
        unit_price: u128,
        //product_id_generator: &mut product::ProductIdGenerator,
        //ctx: &mut tx_context::TxContext,
    ) {
        let product_created = product_create_logic::verify(
            name,
            unit_price,
            //product_id_generator,
            //ctx,
        );
        let product = product_create_logic::mutate(
            &product_created,
            //product_id_generator,
            //ctx,
        );
        //product::set_product_created_id(&mut product_created, product::id(&product));
        //product::freeze_object(product);
        product::add_product(product);
        product::emit_product_created(product_created);
    }

    // public fun borrow_tables(product_id: String): &Tables acquires Tables {
    //     let tables = borrow_global<Tables>(genesis_account::resouce_account_address());
    //     tables
    // }
    /*
40 |         let tables = borrow_global<Tables>(genesis_account::resouce_account_address());
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                      |             |
   |                      |             The type '(aptos_demo=...)::product::Tables' was not declared in the current module. Global storage access is internal to the module'
   |                      Invalid call to borrow_global.    
    */
}
