// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::product_updated {

    use aptos_demo::product::{Self, ProductUpdated};
    use std::string::String;

    public fun product_id(product_updated: &ProductUpdated): String {
        product::product_updated_product_id(product_updated)
    }

    public fun name(product_updated: &ProductUpdated): String {
        product::product_updated_name(product_updated)
    }

    public fun unit_price(product_updated: &ProductUpdated): u128 {
        product::product_updated_unit_price(product_updated)
    }

}
