// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::product_event {

    use aptos_demo::product::{Self, ProductEvent};
    use std::string::String;

    public fun event_type(product_event: &ProductEvent): u8 {
        product::product_event_event_type(product_event)
    }

    public fun product_id(product_event: &ProductEvent): String {
        product::product_event_product_id(product_event)
    }

    public fun name(product_event: &ProductEvent): String {
        product::product_event_name(product_event)
    }

    public fun unit_price(product_event: &ProductEvent): u128 {
        product::product_event_unit_price(product_event)
    }

}
