// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module aptos_demo::registered {

    use aptos_demo::domain_name::{Self, DomainNameId, Registered};

    public fun domain_name_id(registered: &Registered): DomainNameId {
        domain_name::registered_domain_name_id(registered)
    }

    public fun registration_period(registered: &Registered): u64 {
        domain_name::registered_registration_period(registered)
    }

    public fun owner(registered: &Registered): address {
        domain_name::registered_owner(registered)
    }

}
