spring:
  datasource:
    url: jdbc:mysql://localhost/test3?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 1023

rooch:
  contract:
    address: "0xf8e38d63a5208d499725e7ac4851c4a0836e45e2230041b7e3cf43e4738c47b4"
    jsonrpc:
      url: "http://127.0.0.1:50051"
#    pull-day-summary-events:
#      day-summary-created:
#        fixed-delay: 6000
#    pull-order-v2-events:
#      order-v2-created:
#        fixed-delay: 6000
