spring:
  datasource:
    url: jdbc:mysql://localhost/test3?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

server:
  port: 1023

rooch:
  contract:
    address: "0x79bc05885dfdb3c9070e46cc24a1572d98107ffea8da60a742ab8da16b8b81a4"
    jsonrpc:
      url: "http://127.0.0.1:50051"
#    pull-day-summary-events:
#      day-summary-created:
#        fixed-delay: 6000
#    pull-order-v2-events:
#      order-v2-created:
#        fixed-delay: 6000
