// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.taskservice;

import org.dddml.suidemocontracts.sui.contract.service.DaySummaryEventService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class PullDaySummaryEventsTaskService {

    @Autowired
    private DaySummaryEventService daySummaryEventService;

    @Scheduled(fixedDelayString = "${sui.contract.pull-day-summary-events.day-summary-created-fixed-delay:5000}")
    public void pullDaySummaryCreatedEvents() {
        daySummaryEventService.pullDaySummaryCreatedEvents();
    }

}
