// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.taskservice;

import org.dddml.suidemocontracts.sui.contract.service.DomainNameEventService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class PullDomainNameEventsTaskService {

    @Autowired
    private DomainNameEventService domainNameEventService;

    @Scheduled(fixedDelayString = "${sui.contract.pull-domain-name-events.registered.fixed-delay:5000}")
    public void pullRegisteredEvents() {
        domainNameEventService.pullRegisteredEvents();
    }

    @Scheduled(fixedDelayString = "${sui.contract.pull-domain-name-events.renewed.fixed-delay:5000}")
    public void pullRenewedEvents() {
        domainNameEventService.pullRenewedEvents();
    }

}
