// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.taskservice;

import org.dddml.suidemocontracts.sui.contract.repository.*;
import org.dddml.suidemocontracts.sui.contract.service.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UpdateDaySummaryStateTaskService {

    @Autowired
    private SuiDaySummaryService suiDaySummaryService;

    @Autowired
    private DaySummaryEventRepository daySummaryEventRepository;

    @Autowired
    private DaySummaryEventService daySummaryEventService;

    @Scheduled(fixedDelayString = "${sui.contract.update-day-summary-states.fixed-delay:5000}")
    @Transactional
    public void updateDaySummaryStates() {
        daySummaryEventRepository.findByStatusIsNull().forEach(e -> {
            String objectId = e.getId_();
            suiDaySummaryService.updateDaySummaryState(objectId);
            daySummaryEventService.updateStatusToProcessed(e);
        });
    }
}
