// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.service;

import com.github.wubuku.sui.utils.SuiJsonRpcClient;
import org.dddml.suidemocontracts.domain.*;
import org.dddml.suidemocontracts.domain.daysummary.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;

@Service
public class SuiDaySummaryService {

    @Autowired
    private DaySummaryStateRepository daySummaryStateRepository;

    private SuiDaySummaryStateRetriever suiDaySummaryStateRetriever;

    @Autowired
    public SuiDaySummaryService(SuiJsonRpcClient suiJsonRpcClient) {
        this.suiDaySummaryStateRetriever = new SuiDaySummaryStateRetriever(suiJsonRpcClient,
                day -> (DaySummaryState.MutableDaySummaryState)
                        daySummaryStateRepository.get(day, false)
        );
    }

    @Transactional
    public void updateDaySummaryState(String objectId) {
        DaySummaryState daySummaryState = suiDaySummaryStateRetriever.retrieveDaySummaryState(objectId);
        daySummaryStateRepository.save(daySummaryState);
    }


}

