// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.service;

import com.github.wubuku.sui.bean.GetMoveObjectDataResponse;
import com.github.wubuku.sui.utils.SuiJsonRpcClient;
import org.dddml.suidemocontracts.domain.Day;
import org.dddml.suidemocontracts.domain.daysummary.DaySummaryState;
import org.dddml.suidemocontracts.sui.contract.DaySummary;
import org.dddml.suidemocontracts.sui.contract.DomainBeanUtils;

import java.util.function.Function;

public class SuiDaySummaryStateRetriever {

    private SuiJsonRpcClient suiJsonRpcClient;

    private Function<Day, DaySummaryState.MutableDaySummaryState> daySummaryStateFactory;

    public SuiDaySummaryStateRetriever(SuiJsonRpcClient suiJsonRpcClient,
                                       Function<Day, DaySummaryState.MutableDaySummaryState> daySummaryStateFactory
    ) {
        this.suiJsonRpcClient = suiJsonRpcClient;
        this.daySummaryStateFactory = daySummaryStateFactory;
    }

    public DaySummaryState retrieveDaySummaryState(String objectId) {
        GetMoveObjectDataResponse<DaySummary> getObjectDataResponse = suiJsonRpcClient.getMoveObject(
                objectId, DaySummary.class
        );

        DaySummary daySummary = getObjectDataResponse.getDetails().getData().getFields();
        return toDaySummaryState(daySummary);
    }

    private DaySummaryState toDaySummaryState(DaySummary daySummary) {
        DaySummaryState.MutableDaySummaryState daySummaryState = daySummaryStateFactory.apply(DomainBeanUtils.toDay(daySummary.getDay()));
        daySummaryState.setId_(daySummary.getId().getId());
        daySummaryState.setVersion(daySummary.getVersion());
        daySummaryState.setDescription(daySummary.getDescription());
        daySummaryState.setMetadata(daySummary.getMetadata());
        //todo daySummaryState.setArrayData(daySummary.getArrayData());
        daySummaryState.setOptionalData(daySummary.getOptionalData());
        return daySummaryState;
    }


}

