// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.service;

import com.github.wubuku.sui.bean.*;
import com.github.wubuku.sui.utils.*;
import org.dddml.suidemocontracts.domain.order.*;
import org.dddml.suidemocontracts.sui.contract.*;

import java.util.*;
import java.math.*;
import java.util.function.*;

public class SuiOrderStateRetriever {

    private SuiJsonRpcClient suiJsonRpcClient;

    private Function<String, OrderState.MutableOrderState> orderStateFactory;
    private BiFunction<OrderState, String, OrderItemState.MutableOrderItemState> orderItemStateFactory;

    public SuiOrderStateRetriever(SuiJsonRpcClient suiJsonRpcClient,
                                  Function<String, OrderState.MutableOrderState> orderStateFactory,
                                  BiFunction<OrderState, String, OrderItemState.MutableOrderItemState> orderItemStateFactory
    ) {
        this.suiJsonRpcClient = suiJsonRpcClient;
        this.orderStateFactory = orderStateFactory;
        this.orderItemStateFactory = orderItemStateFactory;
    }

    public OrderState retrieveOrderState(String objectId) {
        GetMoveObjectDataResponse<Order> getObjectDataResponse = suiJsonRpcClient.getMoveObject(
                objectId, Order.class
        );

        Order order = getObjectDataResponse.getDetails().getData().getFields();
        return toOrderState(order);
    }


    private OrderState toOrderState(Order order) {
        // new aggregate root state instance
        OrderState.MutableOrderState orderState = orderStateFactory.apply(order.getId().getId());
        orderState.setVersion(order.getVersion()); // on-chain version
        orderState.setTotalAmount(order.getTotalAmount());

        // /////////// get inner entity items /////////////
        String itemsTableId = order.getItems().getFields().getId().getId();
        List<OrderItem> items = getItems(itemsTableId);
        for (OrderItem item : items) {
            orderState.getItems().add(toOrderItemState(orderState, item));
        }
        // ///////////////////////////////////////////////

        return orderState;
    }

    private OrderItemState toOrderItemState(OrderState orderState, OrderItem item) {
        // new inner entity state instance
        OrderItemState.MutableOrderItemState orderItemState = orderItemStateFactory.apply(orderState, item.getProductId());
        orderItemState.setProductId(item.getProductId());
        orderItemState.setQuantity(item.getQuantity());
        orderItemState.setItemAmount(item.getItemAmount());

        // ////// no inner entity in the entity //////
        // ///////////////////////////////////////////

        return orderItemState;
    }

    private List<OrderItem> getItems(String orderItemTableId) {
        List<OrderItem> orderItems = new ArrayList<>();
        String cursor = null;
        while (true) {
            DynamicFieldPage orderItemFieldPage = suiJsonRpcClient.getDynamicFields(orderItemTableId, cursor, null);
            for (DynamicFieldInfo orderItemFieldInfo : orderItemFieldPage.getData()) {
            
                String fieldObjectId = orderItemFieldInfo.getObjectId();
                GetMoveObjectDataResponse<OrderItemDynamicField> getOrderItemFieldResponse
                        = suiJsonRpcClient.getMoveObject(fieldObjectId, OrderItemDynamicField.class);
                OrderItem orderItem = getOrderItemFieldResponse
                        .getDetails().getData().getFields().getValue().getFields();
                orderItems.add(orderItem);
            }
            cursor = orderItemFieldPage.getNextCursor();
            if (cursor == null) {
                break;
            }
        }
        return orderItems;
    }
}

