// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.service;

import com.github.wubuku.sui.utils.SuiJsonRpcClient;
import org.dddml.suidemocontracts.domain.orderv2.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;

@Service
public class SuiOrderV2Service {

    @Autowired
    private OrderV2StateRepository orderV2StateRepository;

    private SuiOrderV2StateRetriever suiOrderV2StateRetriever;

    @Autowired
    public SuiOrderV2Service(SuiJsonRpcClient suiJsonRpcClient) {
        this.suiOrderV2StateRetriever = new SuiOrderV2StateRetriever(suiJsonRpcClient,
                //todo refactor factories???
                orderId -> (OrderV2State.MutableOrderV2State)
                        orderV2StateRepository.get(orderId, false),
                (orderV2State, productId) -> (OrderV2ItemState.MutableOrderV2ItemState)
                        ((AbstractOrderV2ItemStateCollection) orderV2State.getItems()).getOrAdd(productId),
                (orderV2State, shipGroupSeqId) -> (OrderShipGroupState.MutableOrderShipGroupState)
                        ((AbstractOrderShipGroupStateCollection) orderV2State.getOrderShipGroups()).getOrAdd(shipGroupSeqId),
                (orderShipGroupState, productId) -> (OrderItemShipGroupAssociationState.MutableOrderItemShipGroupAssociationState)
                        ((AbstractOrderItemShipGroupAssociationStateCollection) orderShipGroupState.getOrderItemShipGroupAssociations()).getOrAdd(productId)
        );
    }

    @Transactional
    public void updateOrderV2State(String objectId) {
        OrderV2State orderV2State = suiOrderV2StateRetriever.retrieveOrderV2State(objectId);
        orderV2StateRepository.save(orderV2State);
    }


}

