// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.suidemocontracts.sui.contract.service;

import com.github.wubuku.sui.utils.SuiJsonRpcClient;
import org.dddml.suidemocontracts.domain.*;
import org.dddml.suidemocontracts.domain.product.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;

@Service
public class SuiProductService {

    @Autowired
    private ProductStateRepository productStateRepository;

    private SuiProductStateRetriever suiProductStateRetriever;

    @Autowired
    public SuiProductService(SuiJsonRpcClient suiJsonRpcClient) {
        this.suiProductStateRetriever = new SuiProductStateRetriever(suiJsonRpcClient,
                productId -> (ProductState.MutableProductState)
                        productStateRepository.get(productId, false)
        );
    }

    @Transactional
    public void updateProductState(String objectId) {
        ProductState productState = suiProductStateRetriever.retrieveProductState(objectId);
        productStateRepository.save(productState);
    }


}

