spring:
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX
    default-property-inclusion: NON_EMPTY

  messages:
    encoding: UTF-8
    basename: i18n/messages
  mvc:
    static-path-pattern: /**
    servlet:
      load-on-startup: -1
      path: /api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8020/api/.well-known/jwks.json # 1
        authorities-store:
          url: http://localhost:8020/api/.well-known/dddml-wms-restful/authorities # 2
server:
  compression:
    enabled: true
    min-response-size: 20480  #20K more with gzip on
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  max-http-header-size: 81920

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456
server:
  port: 1023

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456
server:
  port: 1023

---
spring:
  profiles: yang
  datasource:
    url: jdbc:mysql://localhost/test2?characterEncoding=utf8&serverTimezone=GMT%2b0&useLegacyDatetimeCode=false
    username: root
    password: 123456
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - com.syj.security.resourceserver.OAuth2ResourceServerSecurityConfig

server:
  port: 1023

